<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <EnableDynamicLoading>true</EnableDynamicLoading>

    <RootNamespace>NightFall</RootNamespace>

    <Nullable>enable</Nullable>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Meziantou.Analyzer" Version="3.0.177">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime;
        build;
        native;
        contentfiles;
        analyzers;
        buildtransitive
      </IncludeAssets>
    </PackageReference>

    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime;
        build;
        native;
        contentfiles;
        analyzers;
        buildtransitive
      </IncludeAssets>
    </PackageReference>

    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime;
        build;
        native;
        contentfiles;
        analyzers;
        buildtransitive
      </IncludeAssets>
    </PackageReference>

  </ItemGroup>

</Project>